apiVersion: v1
kind: Service
metadata:
  name: theia
spec:
  type: ClusterIP
  selector:
    app: theia
  ports:
    - name: theia
      protocol: TCP
      port: 3000
    - name: web
      protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: theia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - name: theia
        image: drighart/workbench-quasar-theia:latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 75m
            memory: 512Mi
        ports:
        - name: theia
          containerPort: 3000
        - name: web
          containerPort: 8080
