name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print env
      run: |
        env | sort

    - name: npm install, build, and test
      run: |
        npm install
        npm install -g @quasar/cli
        npm run build --if-present
        quasar build -m pwa
        ls -l
      env:
        CI: true

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.2.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist/pwa

#    - name: Publish to Netlify
#      uses: netlify/actions/build@master
#      env:
#        NETLIFY_BASE: quasar-example-2
#        NETLIFY_CMD: quasar build -m pwa
#        NETLIFY_DIR: dist/pwa

#    - name: Publish to Registry
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: drighart/github-actions-example
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
